FROM scratch
LABEL maintainer="Clement Verna <cverna@fedoraproject.org>"
ENV DISTTAG=f31-updates-candidatecontainer FGC=f31-updates-candidate FBR=f31-updates-candidate
ADD fedora-31-updates-candidate-ppc64le-20200427.tar.xz /
CMD ["/bin/bash"]