FROM scratch
LABEL maintainer="Clement Verna <cverna@fedoraproject.org>"
ENV DISTTAG=f33-updates-candidatecontainer FGC=f33-updates-candidate FBR=f33-updates-candidate
ADD fedora-33-updates-candidate-s390x-20200220.tar.xz /
CMD ["/bin/bash"]