FROM scratch
LABEL maintainer="Clement Verna <cverna@fedoraproject.org>"
ENV DISTTAG=f32-updates-candidatecontainer FGC=f32-updates-candidate FBR=f32-updates-candidate
ADD fedora-32-updates-candidate-aarch64-20200220.tar.xz /
CMD ["/bin/bash"]